In [101]:
#NumPy - Numerical Python
#NumPy is a Python library used for working with arrays.
#Advatanges of working wiht NumPy Arrays.
# 1) NumPy is faster than Python List
# 2) NumPy uses less memory to store data
# 3) Faster operations on NumPy Arrays

In [1]:
import numpy as np

In [103]:
# List vs NumPy time taken to perform the same operation
from time import process_time

In [104]:
# Time taken by List
pythonLst = [i for i in range(10000)]
startTime = process_time()

pythonLst = [i+5 for i in pythonLst]
endTime = process_time()

amnTime = endTime - startTime
print("Time taken by List: ", amnTime)

Time taken by List:  0.0006769999999995946


In [105]:
#Time taken by NumPy
npArr = np.array([i for i in range(10000)])
startTime = process_time()

npArr += 5
endTime = process_time()

amnTime = endTime - startTime
print("Time taken by NumPy: ", amnTime)

Time taken by NumPy:  0.00045800000000006946


In [106]:
#NumPy Arrays
#list 

lst = [1,2,3,4,5] 
print(lst) #values are seprated by commas
type(lst)

[1, 2, 3, 4, 5]


list

In [107]:
#NumPy Array
arr = np.array([1,2,3,4,5]) 
print(arr) #values are not seprated by comma
type(arr) #numpy.ndarray , n-dimensional array

[1 2 3 4 5]


numpy.ndarray

In [108]:
#creating a 1-D Array

arr1 = np.array([1,2,3,4,5])
print(arr1)
arr1.shape #5 coulmns and 1 row

[1 2 3 4 5]


(5,)

In [109]:
# creating a 2-D Array

arr2 = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)]) #instead of () we could also use []
print(arr2)
arr2.shape #(4,3) -> (rows,columns) 4 rows and 3 columns

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [110]:
arr3 = np.array([[1,2,3,4],[5,6,7,9]], dtype='float')
print(arr3)


[[1. 2. 3. 4.]
 [5. 6. 7. 9.]]


In [111]:
#Initial Placeholders in NumPy Arrays
#creating a numpy array with all zeros

x = np.zeros((4,5), dtype=int)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [112]:
#creating npmoy array with all ones

y = np.ones((3,4), dtype=int)
print(y)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [113]:
#creating a numpy array with a particular number

z = np.full((5,4),5 ,dtype=int)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [114]:
#create an identity matrix

a =np.eye(5 , dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [115]:
#create a numPy Array with randome vlues

b = np.random.random((3,4)) #random values between 0 and 1
print(b)

[[0.69537446 0.39119789 0.25282644 0.20463775]
 [0.40198445 0.09239871 0.9362837  0.04073165]
 [0.58203179 0.29741728 0.08792938 0.37719986]]


In [10]:
#create random integor values numpy array

c = np.random.randint(1,10, (3,4)) #random values between 1 and 100
print(c)

[[2 3 9 4]
 [9 9 7 4]
 [8 9 4 9]]


In [117]:
#creating NumPy array of evenly spaced values

x = np.linspace(10,30,6 ,dtype=int) #start, stop, number of values
print(x)

[10 14 18 22 26 30]


In [5]:
#evenly spaced values with a step

y = np.arange(10,30,5) #start, stop, step
print(y)

z = np.arange(5) 
print(z)

[10 15 20 25]
[0 1 2 3 4]


In [119]:
#convert a list to a NumPy Array

lst = [10,20,30,40,50]
npArr = np.asarray(lst)
print(npArr)
type(npArr)

[10 20 30 40 50]


numpy.ndarray

In [120]:
#convert tuple to NumPy Array

tpl = (10,120,130,140,150)
npArr = np.asarray(tpl)
print(npArr)
type(npArr)

[ 10 120 130 140 150]


numpy.ndarray

In [7]:
#Anlyzing NumPy Array
c = np.random.randint(10,90,(5,5))
print(c)

d = np.random.randint(10,20,5) #1-D array
print(d)

[[46 54 62 70 11]
 [84 49 17 19 50]
 [62 31 33 67 71]
 [24 60 41 14 20]
 [31 80 58 76 83]]
[15 16 15 15 12]


In [122]:
#array dimensions
c.shape

(5, 5)

In [123]:
#number of dimensions
c.ndim

2

In [124]:
#number of elements
c.size

25

In [125]:
#checking the datatype of values in the array
c.dtype

dtype('int64')

In [126]:
#Mathematical Operations on NumPy Arrays

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) #concatenation of two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [127]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

#Addition of two NumPy Arrays
print(a + b)
#other way of adding two numpy arrays
print(np.add(a,b))

#Subtraction of two NumPy Arrays
print(a - b)
#other way of subtracting two numpy arrays
print(np.subtract(a,b))

#Multiplication of two NumPy Arrays (element wise)
print(a * b)
#other way of multiplying two numpy arrays
print(np.multiply(a,b))

#Division of two NumPy Arrays (element wise)
print(a / b)
#other way of dividing two numpy arrays
print(np.divide(a,b))


[[9 9 9]
 [4 9 3]
 [6 4 4]]
[[13 18 11]
 [10 19 19]
 [16 12 18]]
[[22 27 20]
 [14 28 22]
 [22 16 22]]
[[22 27 20]
 [14 28 22]
 [22 16 22]]
[[ -4  -9  -2]
 [ -6 -10 -16]
 [-10  -8 -14]]
[[ -4  -9  -2]
 [ -6 -10 -16]
 [-10  -8 -14]]
[[117 162  99]
 [ 40 171  57]
 [ 96  48  72]]
[[117 162  99]
 [ 40 171  57]
 [ 96  48  72]]
[[0.69230769 0.5        0.81818182]
 [0.4        0.47368421 0.15789474]
 [0.375      0.33333333 0.22222222]]
[[0.69230769 0.5        0.81818182]
 [0.4        0.47368421 0.15789474]
 [0.375      0.33333333 0.22222222]]


In [128]:
#Array Manipulation

npArr = np.random.randint(0,10,(2,3))
print(npArr)
print(npArr.shape)

#transpose of an array
tranArray = np.transpose(npArr)
print(tranArray)
print(tranArray.shape)

[[5 5 7]
 [0 6 7]]
(2, 3)
[[5 0]
 [5 6]
 [7 7]]
(3, 2)


In [129]:
#Another way to find transpose
npArr = np.random.randint(0,10,(2,3))
print(npArr)
print(npArr.shape)

npArr2 = npArr.T
print(npArr2)
print(npArr2.shape)


[[4 7 8]
 [3 5 2]]
(2, 3)
[[4 3]
 [7 5]
 [8 2]]
(3, 2)


In [130]:
#Reshape an array
npArr = np.random.randint(0,10,(2,3))
print(npArr)
print(npArr.shape)

b = npArr.reshape(3,2) #Not Like transpose
print(b)
print(b.shape) 

[[1 8 6]
 [0 8 1]]
(2, 3)
[[1 8]
 [6 0]
 [8 1]]
(3, 2)
